spring.application.name=agentic-ai

# ===============================
# OPENAI CONFIGURATION
# ===============================

# Use environment variable for security
spring.ai.openai.api-key=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

# Model to use
spring.ai.openai.chat.options.model=gpt-4o-mini

# Optional settings
spring.ai.openai.chat.options.temperature=0.7
spring.ai.openai.chat.options.max-tokens=500


# ===============================
# SERVER CONFIG
# ===============================

server.port=8080


# ===============================
# LOGGING
# ===============================

logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.web=INFO

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

spring.data.mongodb.uri=mongodb+srv://deshibaji20_db_user:diLAHpyX03wsg2PK@cluster0.zw6tkrw.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=auditdb