spring.application.name=agentic-ai

# ===============================
# OPENAI CONFIGURATION
# ===============================

# Use environment variable for security
spring.ai.openai.api-key=

# Model to use
spring.ai.openai.chat.options.model=gpt-4o-mini

# Optional settings
spring.ai.openai.chat.options.temperature=0.7
spring.ai.openai.chat.options.max-tokens=500


# ===============================
# SERVER CONFIG
# ===============================

server.port=8080


# ===============================
# LOGGING
# ===============================

logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.web=INFO

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

spring.data.mongodb.uri=
spring.data.mongodb.database=auditdb